id: P008040
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS17111
  title: ལག་ལེན་སོ་བདུན་མ་དང་ཀློང་ཆེན་སྙིང་ཐིག
  author: ''
  volumes:
    74b928536a3f4053b0bd63914c5d6e47:
      image_group_id: I8LS17117
      title: Volume 1 of lag len so bdun ma dang klong chen snying thig
      volume_number: 1
      total_pages: 92
      base_file: v001.txt
