id: P008040
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17111
  title: ལག་ལེན་སོ་བདུན་མ་དང་ཀློང་ཆེན་སྙིང་ཐིག
  author: ''
  volumes:
    89d5e80c51ad4af9a5be20194ed5c443:
      image_group_id: I8LS17117
      title: ''
      volume_number: 1
      total_pages: 92
ebook_metadata:
  title: ལག་ལེན་སོ་བདུན་མ་དང་ཀློང་ཆེན་སྙིང་ཐིག
  author: ''
  sku: P008040
  cover: cover.jpg
  layers:
  - pagination
