id: I20791007
legacy_id: P008040
ocr_import_info:
  bdrc_scan_id: W8LS17111
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T03:28:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:42:10.116953+00:00'
last_modified: 2022-09-04 11:42:15.553858
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17111
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17111
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལག་ལེན་སོ་བདུན་མ་དང་ཀློང་ཆེན་སྙིང་ཐིག
  author: ཀུན་མཁྱེན་འཇིགས་མེད་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.5699112306692746
  ocr_word_median_confidence_index: 0.5600000023841858
quality: null
bases:
  I8LS17117:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17117
      total_pages: 92
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17117.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5699112306692746
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
